version: "3.8"

services:
  node:
    build:
      context: .
      target: build
      args:
        - MIX_ENV=dev
    command: mix phx.server
    restart: unless-stopped
    ports:
      - "4000-4009:4000"
    volumes:
      - .:/app

